import { Flashcard, VocabList, WordType } from './types';
import { createCommonVerbCards } from './commonVerbs';

type SeedCard = {
  term: string;
  tr: string;
  type: WordType;
  level: 'B2' | 'C1';
  example: string;
  exampleTr: string;
  note?: string;
  pattern?: string;
  natural?: string;
  formal?: string;
  intent?: string;
  synonyms?: string;
  collocations?: string;
};

function encodeLookup(value: string): string {
  return encodeURIComponent(value.trim());
}

function inferCardKind(type: WordType): Flashcard['cardKind'] {
  if (type === 'collocation') return 'collocation';
  if (type === 'phrase' || type === 'idiom') return 'speakingFunction';
  if (type === 'phrasalVerb') return 'production';
  return 'meaning';
}

function card(seed: SeedCard, index: number, prefix: string): Flashcard {
  const isPhraseLike = ['phrase', 'phrasalVerb', 'idiom', 'collocation'].includes(seed.type);
  const lookupTerm = encodeLookup(seed.term);

  return {
    id: `${prefix}_${index}`,
    term: seed.term,
    translationTr: seed.tr,
    wordType: seed.type,
    cardKind: inferCardKind(seed.type),
    level: seed.level,
    prompt: seed.type === 'collocation' && seed.pattern ? seed.pattern.replace(seed.term, '___') : undefined,
    answer: seed.type === 'collocation' ? seed.term : undefined,
    example: seed.example,
    exampleTranslation: seed.exampleTr,
    note: [seed.note, seed.synonyms ? `Synonyms: ${seed.synonyms}` : '', seed.collocations ? `Collocations: ${seed.collocations}` : '']
      .filter(Boolean)
      .join('\n'),
    phraseForms: isPhraseLike
      ? {
          pattern: seed.pattern || seed.term,
          naturalVariant: seed.natural || '',
          formalVariant: seed.formal || '',
          usageIntent: seed.intent || '',
        }
      : undefined,
    verbForms:
      seed.type === 'verb' || seed.type === 'phrasalVerb'
        ? {
            baseForm: seed.term,
            usagePattern: seed.pattern || '',
          }
        : undefined,
    adjectiveForms:
      seed.type === 'adjective'
        ? {
            usage: seed.pattern || '',
          }
        : undefined,
    sourceTags: [
      seed.level === 'C1' ? 'Oxford5000-C1' : 'Oxford5000-B2',
      seed.type === 'collocation' ? 'Collocation' : '',
      seed.type === 'phrase' ? 'Speaking' : '',
      seed.type === 'phrasalVerb' ? 'PhrasalVerb' : '',
      seed.type === 'idiom' ? 'NaturalEnglish' : '',
    ].filter(Boolean),
    usageLinks: [
      {
        label: 'Cambridge',
        url: `https://dictionary.cambridge.org/dictionary/english/${lookupTerm}`,
      },
      {
        label: 'Oxford',
        url: `https://www.oxfordlearnersdictionaries.com/definition/english/${lookupTerm}`,
      },
      {
        label: 'YouGlish',
        url: `https://youglish.com/pronounce/${lookupTerm}/english`,
      },
      {
        label: 'Forvo',
        url: `https://forvo.com/search/${lookupTerm}/en/`,
      },
    ],
  };
}

function mapCards(prefix: string, seeds: SeedCard[]): Flashcard[] {
  return seeds.map((seed, index) => card(seed, index, prefix));
}

const b2Vocabulary: SeedCard[] = [
  {
    term: 'substantial',
    tr: 'önemli, kayda değer, büyük miktarda',
    type: 'adjective',
    level: 'B2',
    pattern: 'a substantial increase / amount / difference',
    example: 'The new policy led to a substantial increase in applications.',
    exampleTr: 'Yeni politika başvurularda kayda değer bir artışa yol açtı.',
    synonyms: 'considerable, significant',
    collocations: 'substantial evidence, substantial progress',
  },
  {
    term: 'reluctant',
    tr: 'isteksiz, gönülsüz',
    type: 'adjective',
    level: 'B2',
    pattern: 'reluctant to do something',
    example: 'She was reluctant to commit to a deadline before seeing the full scope.',
    exampleTr: 'Tüm kapsamı görmeden teslim tarihine bağlanma konusunda isteksizdi.',
    synonyms: 'hesitant, unwilling',
  },
  {
    term: 'mitigate',
    tr: 'hafifletmek, azaltmak',
    type: 'verb',
    level: 'B2',
    pattern: 'mitigate a risk / impact / problem',
    example: 'We need a backup plan to mitigate the risk of delays.',
    exampleTr: 'Gecikme riskini azaltmak için bir yedek plana ihtiyacımız var.',
    synonyms: 'reduce, soften, alleviate',
  },
  {
    term: 'constraint',
    tr: 'kısıt, sınırlama',
    type: 'noun',
    level: 'B2',
    example: 'Budget constraints forced the team to simplify the launch plan.',
    exampleTr: 'Bütçe kısıtları ekibi lansman planını sadeleştirmeye zorladı.',
    collocations: 'time constraints, budget constraints, technical constraints',
  },
  {
    term: 'trade-off',
    tr: 'denge tercihi, bir şeyden vazgeçip diğerini seçme durumu',
    type: 'noun',
    level: 'B2',
    example: 'There is always a trade-off between speed and accuracy.',
    exampleTr: 'Hız ile doğruluk arasında her zaman bir denge tercihi vardır.',
    collocations: 'make a trade-off, an acceptable trade-off',
  },
  {
    term: 'to some extent',
    tr: 'bir ölçüde, kısmen',
    type: 'phrase',
    level: 'B2',
    intent: 'Fikrini yumuşatmak veya genellemeyi sınırlamak',
    example: 'I agree with the proposal to some extent, but the timeline is unrealistic.',
    exampleTr: 'Teklife bir ölçüde katılıyorum ama zaman planı gerçekçi değil.',
  },
];

const c1Vocabulary: SeedCard[] = [
  {
    term: 'nuanced',
    tr: 'nüanslı, ince ayrımları olan',
    type: 'adjective',
    level: 'C1',
    pattern: 'a nuanced view / argument / understanding',
    example: 'The article offers a nuanced view of remote work rather than a simple yes-or-no answer.',
    exampleTr: 'Makale uzaktan çalışma hakkında basit bir evet-hayır cevabı yerine nüanslı bir bakış sunuyor.',
    synonyms: 'subtle, refined',
  },
  {
    term: 'scrutinize',
    tr: 'dikkatle incelemek, mercek altına almak',
    type: 'verb',
    level: 'C1',
    pattern: 'scrutinize a claim / report / decision',
    example: 'The committee will scrutinize the report before approving the budget.',
    exampleTr: 'Komite bütçeyi onaylamadan önce raporu dikkatle inceleyecek.',
    synonyms: 'examine closely, inspect',
  },
  {
    term: 'shortcomings',
    tr: 'eksiklikler, kusurlar',
    type: 'noun',
    level: 'C1',
    example: 'The prototype works, but its shortcomings become clear under heavy use.',
    exampleTr: 'Prototip çalışıyor ama yoğun kullanımda eksiklikleri ortaya çıkıyor.',
    collocations: 'address shortcomings, serious shortcomings',
  },
  {
    term: 'counterproductive',
    tr: 'ters etki yaratan, amaca zarar veren',
    type: 'adjective',
    level: 'C1',
    example: 'Adding more meetings may be counterproductive if the team needs focus time.',
    exampleTr: 'Ekip odaklanma zamanına ihtiyaç duyuyorsa daha fazla toplantı eklemek ters etki yaratabilir.',
    synonyms: 'harmful, self-defeating',
  },
  {
    term: 'by and large',
    tr: 'genel olarak, büyük ölçüde',
    type: 'phrase',
    level: 'C1',
    intent: 'Genel değerlendirme yapmak',
    example: 'By and large, the migration went smoothly.',
    exampleTr: 'Genel olarak geçiş sorunsuz ilerledi.',
  },
  {
    term: 'arguably',
    tr: 'denebilir ki, tartışmalı olsa da muhtemelen',
    type: 'adverb',
    level: 'C1',
    example: 'This is arguably the most important decision we have made this year.',
    exampleTr: 'Bu, denebilir ki bu yıl aldığımız en önemli karar.',
    note: 'Kesin iddia yerine güçlü ama tartışmaya açık bir iddia kurar.',
  },
];

const phrasalVerbs: SeedCard[] = [
  {
    term: 'bring up',
    tr: 'konuyu açmak, gündeme getirmek',
    type: 'phrasalVerb',
    level: 'B2',
    pattern: 'bring up an issue / point / concern',
    example: 'I did not want to bring up the budget issue during the client call.',
    exampleTr: 'Müşteri görüşmesinde bütçe konusunu gündeme getirmek istemedim.',
    natural: 'mention',
  },
  {
    term: 'figure out',
    tr: 'çözmek, anlamak',
    type: 'phrasalVerb',
    level: 'B2',
    pattern: 'figure out how / why / what',
    example: 'We need to figure out why users drop off after onboarding.',
    exampleTr: 'Kullanıcıların onboarding sonrası neden ayrıldığını anlamamız gerekiyor.',
    formal: 'determine',
  },
  {
    term: 'phase out',
    tr: 'kademeli olarak kullanımdan kaldırmak',
    type: 'phrasalVerb',
    level: 'C1',
    pattern: 'phase out a system / product / practice',
    example: 'The company plans to phase out the old dashboard by September.',
    exampleTr: 'Şirket eski paneli eylül ayına kadar kademeli olarak kaldırmayı planlıyor.',
  },
  {
    term: 'push back on',
    tr: 'itiraz etmek, karşı çıkmak',
    type: 'phrasalVerb',
    level: 'C1',
    pattern: 'push back on a proposal / assumption / deadline',
    example: 'The engineers pushed back on the deadline because the scope had changed.',
    exampleTr: 'Mühendisler kapsam değiştiği için teslim tarihine itiraz etti.',
  },
];

const idioms: SeedCard[] = [
  {
    term: 'a blessing in disguise',
    tr: 'ilk başta kötü görünüp sonradan iyi sonuç veren şey',
    type: 'idiom',
    level: 'B2',
    example: 'Losing that client was a blessing in disguise; it gave us time to fix the product.',
    exampleTr: 'O müşteriyi kaybetmek sonradan iyiye döndü; ürünü düzeltmek için bize zaman verdi.',
  },
  {
    term: 'the tip of the iceberg',
    tr: 'buzdağının görünen kısmı',
    type: 'idiom',
    level: 'B2',
    example: 'The reported bugs are just the tip of the iceberg.',
    exampleTr: 'Raporlanan hatalar buzdağının sadece görünen kısmı.',
  },
  {
    term: 'move the needle',
    tr: 'gerçek bir fark yaratmak',
    type: 'idiom',
    level: 'C1',
    example: 'Changing the button color will not move the needle; we need to improve activation.',
    exampleTr: 'Buton rengini değiştirmek gerçek fark yaratmaz; aktivasyonu iyileştirmemiz gerekiyor.',
  },
  {
    term: 'read between the lines',
    tr: 'satır aralarını okumak, ima edileni anlamak',
    type: 'idiom',
    level: 'C1',
    example: 'If you read between the lines, the message is that the project is at risk.',
    exampleTr: 'Satır aralarını okursan mesaj şu: proje risk altında.',
  },
];

const collocations: SeedCard[] = [
  {
    term: 'raise awareness',
    tr: 'farkındalık yaratmak',
    type: 'collocation',
    level: 'B2',
    example: 'The campaign aims to raise awareness about data privacy.',
    exampleTr: 'Kampanya veri gizliliği konusunda farkındalık yaratmayı amaçlıyor.',
  },
  {
    term: 'draw a distinction',
    tr: 'ayrım yapmak',
    type: 'collocation',
    level: 'C1',
    example: 'It is important to draw a distinction between correlation and causation.',
    exampleTr: 'Korelasyon ile nedensellik arasında ayrım yapmak önemlidir.',
  },
  {
    term: 'pose a challenge',
    tr: 'zorluk teşkil etmek',
    type: 'collocation',
    level: 'B2',
    example: 'Limited data poses a challenge for accurate forecasting.',
    exampleTr: 'Sınırlı veri doğru tahminleme için zorluk teşkil eder.',
  },
  {
    term: 'reach a consensus',
    tr: 'uzlaşmaya varmak',
    type: 'collocation',
    level: 'C1',
    example: 'After a long discussion, the team reached a consensus.',
    exampleTr: 'Uzun bir tartışmadan sonra ekip uzlaşmaya vardı.',
  },
];

const speakingPatterns: SeedCard[] = [
  {
    term: 'What I am trying to say is...',
    tr: 'Söylemeye çalıştığım şey şu...',
    type: 'phrase',
    level: 'B2',
    intent: 'Kendini açıklamak veya cümleyi toparlamak',
    example: 'What I am trying to say is that we should test the idea before scaling it.',
    exampleTr: 'Söylemeye çalıştığım şey şu: fikri büyütmeden önce test etmeliyiz.',
    natural: 'I mean...',
  },
  {
    term: 'That being said,...',
    tr: 'Bununla birlikte..., yine de...',
    type: 'phrase',
    level: 'B2',
    intent: 'Önceki fikri dengelemek',
    example: 'The product is promising. That being said, the onboarding still needs work.',
    exampleTr: 'Ürün umut verici. Bununla birlikte onboarding hâlâ çalışılmalı.',
    formal: 'Nevertheless,...',
  },
  {
    term: 'I would frame it slightly differently.',
    tr: 'Bunu biraz farklı çerçevelendirirdim.',
    type: 'phrase',
    level: 'C1',
    intent: 'Nazikçe karşı çıkmak veya bakış açısını değiştirmek',
    example: 'I would frame it slightly differently: the issue is not speed, but clarity.',
    exampleTr: 'Bunu biraz farklı çerçevelendirirdim: sorun hız değil, netlik.',
  },
  {
    term: 'Could you elaborate on that?',
    tr: 'Bunu biraz açabilir misin?',
    type: 'phrase',
    level: 'B2',
    intent: 'Daha fazla açıklama istemek',
    example: 'Could you elaborate on that? I want to understand the reasoning behind the decision.',
    exampleTr: 'Bunu biraz açabilir misin? Kararın arkasındaki mantığı anlamak istiyorum.',
  },
  {
    term: 'I see where you are coming from, but...',
    tr: 'Ne demek istediğini anlıyorum ama...',
    type: 'phrase',
    level: 'C1',
    intent: 'Karşı tarafı kabul ederek itiraz etmek',
    example: 'I see where you are coming from, but I do not think the data supports that conclusion.',
    exampleTr: 'Ne demek istediğini anlıyorum ama verinin bu sonucu desteklediğini düşünmüyorum.',
  },
];

const additionalB2Vocabulary: SeedCard[] = [
  {
    term: 'accountable',
    tr: 'sorumlu, hesap verebilir',
    type: 'adjective',
    level: 'B2',
    pattern: 'accountable for something',
    example: 'Each team is accountable for the quality of its own work.',
    exampleTr: 'Her ekip kendi işinin kalitesinden sorumludur.',
    synonyms: 'responsible, answerable',
  },
  {
    term: 'adapt',
    tr: 'uyum sağlamak, uyarlamak',
    type: 'verb',
    level: 'B2',
    pattern: 'adapt to a situation / adapt something for a purpose',
    example: 'The company had to adapt quickly to changing customer expectations.',
    exampleTr: 'Şirket değişen müşteri beklentilerine hızla uyum sağlamak zorunda kaldı.',
    synonyms: 'adjust, modify',
  },
  {
    term: 'adequate',
    tr: 'yeterli, uygun',
    type: 'adjective',
    level: 'B2',
    pattern: 'adequate for something',
    example: 'The current system is adequate for small teams but not for large organizations.',
    exampleTr: 'Mevcut sistem küçük ekipler için yeterli ama büyük organizasyonlar için değil.',
    synonyms: 'sufficient, acceptable',
  },
  {
    term: 'assumption',
    tr: 'varsayım',
    type: 'noun',
    level: 'B2',
    example: 'The plan is based on the assumption that demand will keep growing.',
    exampleTr: 'Plan, talebin artmaya devam edeceği varsayımına dayanıyor.',
    collocations: 'make an assumption, challenge an assumption',
  },
  {
    term: 'beneficial',
    tr: 'faydalı, yararlı',
    type: 'adjective',
    level: 'B2',
    pattern: 'beneficial to / for someone',
    example: 'Regular feedback can be beneficial for long-term improvement.',
    exampleTr: 'Düzenli geri bildirim uzun vadeli gelişim için faydalı olabilir.',
    synonyms: 'useful, advantageous',
  },
  {
    term: 'clarify',
    tr: 'açıklığa kavuşturmak, netleştirmek',
    type: 'verb',
    level: 'B2',
    pattern: 'clarify a point / issue / requirement',
    example: 'Could you clarify what you mean by a successful launch?',
    exampleTr: 'Başarılı lansman derken ne demek istediğini netleştirebilir misin?',
    synonyms: 'explain, make clear',
  },
  {
    term: 'consistent',
    tr: 'tutarlı, düzenli',
    type: 'adjective',
    level: 'B2',
    pattern: 'consistent with something',
    example: 'Your argument is not consistent with the evidence.',
    exampleTr: 'Argümanın kanıtlarla tutarlı değil.',
    synonyms: 'steady, coherent',
  },
  {
    term: 'contribute',
    tr: 'katkıda bulunmak, sebep olmak',
    type: 'verb',
    level: 'B2',
    pattern: 'contribute to something',
    example: 'Lack of communication contributed to the delay.',
    exampleTr: 'İletişim eksikliği gecikmeye katkıda bulundu.',
    collocations: 'contribute significantly, contribute directly',
  },
  {
    term: 'criteria',
    tr: 'kriterler, ölçütler',
    type: 'noun',
    level: 'B2',
    example: 'We need clear criteria before we compare the options.',
    exampleTr: 'Seçenekleri karşılaştırmadan önce net kriterlere ihtiyacımız var.',
    note: 'Tekil biçimi criterion, çoğul biçimi criteria.',
  },
  {
    term: 'demanding',
    tr: 'zorlayıcı, çok emek isteyen',
    type: 'adjective',
    level: 'B2',
    example: 'The course is demanding, but it improves your academic writing quickly.',
    exampleTr: 'Kurs zorlayıcı ama akademik yazını hızlıca geliştirir.',
    synonyms: 'challenging, difficult',
  },
  {
    term: 'derive',
    tr: 'türetmek, elde etmek, kaynaklanmak',
    type: 'verb',
    level: 'B2',
    pattern: 'derive from something',
    example: 'Much of the value derives from the quality of the data.',
    exampleTr: 'Değerin büyük kısmı verinin kalitesinden kaynaklanır.',
  },
  {
    term: 'emerge',
    tr: 'ortaya çıkmak, belirmek',
    type: 'verb',
    level: 'B2',
    example: 'A pattern began to emerge after we reviewed the interview notes.',
    exampleTr: 'Görüşme notlarını inceledikten sonra bir örüntü ortaya çıkmaya başladı.',
    collocations: 'a pattern emerges, evidence emerges',
  },
  {
    term: 'emphasize',
    tr: 'vurgulamak',
    type: 'verb',
    level: 'B2',
    example: 'The speaker emphasized the importance of trust in remote teams.',
    exampleTr: 'Konuşmacı uzaktan ekiplerde güvenin önemini vurguladı.',
    synonyms: 'stress, highlight',
  },
  {
    term: 'evaluate',
    tr: 'değerlendirmek',
    type: 'verb',
    level: 'B2',
    pattern: 'evaluate an option / result / performance',
    example: 'We will evaluate the results after two weeks.',
    exampleTr: 'Sonuçları iki hafta sonra değerlendireceğiz.',
    synonyms: 'assess, judge',
  },
  {
    term: 'evidence',
    tr: 'kanıt, veri, gösterge',
    type: 'noun',
    level: 'B2',
    example: 'There is little evidence that the change improved retention.',
    exampleTr: 'Değişikliğin kullanıcı tutmayı iyileştirdiğine dair az kanıt var.',
    collocations: 'strong evidence, limited evidence, evidence suggests',
  },
  {
    term: 'feasible',
    tr: 'uygulanabilir, yapılabilir',
    type: 'adjective',
    level: 'B2',
    example: 'The idea is interesting, but it may not be feasible with our current budget.',
    exampleTr: 'Fikir ilginç ama mevcut bütçemizle uygulanabilir olmayabilir.',
    synonyms: 'practical, realistic',
  },
  {
    term: 'indicate',
    tr: 'göstermek, işaret etmek',
    type: 'verb',
    level: 'B2',
    pattern: 'indicate that...',
    example: 'The survey indicates that users want a simpler setup.',
    exampleTr: 'Anket, kullanıcıların daha basit bir kurulum istediğini gösteriyor.',
    synonyms: 'show, suggest',
  },
  {
    term: 'inevitable',
    tr: 'kaçınılmaz',
    type: 'adjective',
    level: 'B2',
    example: 'Some resistance is inevitable when a team changes its workflow.',
    exampleTr: 'Bir ekip iş akışını değiştirdiğinde bir miktar direnç kaçınılmazdır.',
    synonyms: 'unavoidable',
  },
  {
    term: 'maintain',
    tr: 'sürdürmek, korumak, iddia etmek',
    type: 'verb',
    level: 'B2',
    example: 'It is difficult to maintain quality when the team is under pressure.',
    exampleTr: 'Ekip baskı altındayken kaliteyi korumak zordur.',
    collocations: 'maintain standards, maintain momentum',
  },
  {
    term: 'obstacle',
    tr: 'engel',
    type: 'noun',
    level: 'B2',
    example: 'The biggest obstacle is not the technology but the lack of alignment.',
    exampleTr: 'En büyük engel teknoloji değil, uyum eksikliği.',
    synonyms: 'barrier, hurdle',
  },
  {
    term: 'outcome',
    tr: 'sonuç, çıktı',
    type: 'noun',
    level: 'B2',
    example: 'The outcome depends on how quickly we can test the idea.',
    exampleTr: 'Sonuç, fikri ne kadar hızlı test edebileceğimize bağlı.',
    collocations: 'desired outcome, likely outcome',
  },
  {
    term: 'priority',
    tr: 'öncelik',
    type: 'noun',
    level: 'B2',
    example: 'Improving speaking confidence is my main priority this month.',
    exampleTr: 'Konuşma özgüvenimi geliştirmek bu ayki ana önceliğim.',
    collocations: 'set priorities, top priority',
  },
  {
    term: 'reliable',
    tr: 'güvenilir',
    type: 'adjective',
    level: 'B2',
    example: 'We need a more reliable way to measure progress.',
    exampleTr: 'Gelişimi ölçmek için daha güvenilir bir yola ihtiyacımız var.',
    synonyms: 'dependable, trustworthy',
  },
  {
    term: 'resolve',
    tr: 'çözmek, karara bağlamak',
    type: 'verb',
    level: 'B2',
    pattern: 'resolve an issue / conflict / problem',
    example: 'The team resolved the issue before it affected users.',
    exampleTr: 'Ekip sorunu kullanıcıları etkilemeden çözdü.',
    synonyms: 'solve, settle',
  },
  {
    term: 'whereas',
    tr: 'oysa, halbuki, buna karşın',
    type: 'phrase',
    level: 'B2',
    intent: 'İki fikri karşılaştırmak',
    example: 'The first option is cheaper, whereas the second one is more reliable.',
    exampleTr: 'İlk seçenek daha ucuz, oysa ikincisi daha güvenilir.',
  },
];

const additionalC1Vocabulary: SeedCard[] = [
  {
    term: 'ambiguous',
    tr: 'belirsiz, birden fazla anlama açık',
    type: 'adjective',
    level: 'C1',
    example: 'The instructions were ambiguous, so different teams interpreted them differently.',
    exampleTr: 'Talimatlar belirsizdi, bu yüzden farklı ekipler onları farklı yorumladı.',
    synonyms: 'unclear, vague',
  },
  {
    term: 'compelling',
    tr: 'ikna edici, güçlü, karşı konulmaz',
    type: 'adjective',
    level: 'C1',
    example: 'The report makes a compelling case for investing in accessibility.',
    exampleTr: 'Rapor, erişilebilirliğe yatırım yapmak için güçlü bir argüman sunuyor.',
    collocations: 'compelling argument, compelling evidence',
  },
  {
    term: 'concede',
    tr: 'kabul etmek, teslim etmek',
    type: 'verb',
    level: 'C1',
    pattern: 'concede that...',
    example: 'I concede that the plan is risky, but doing nothing is riskier.',
    exampleTr: 'Planın riskli olduğunu kabul ediyorum ama hiçbir şey yapmamak daha riskli.',
    note: 'Tartışmada karşı tarafın bir noktasını kabul etmek için kullanılır.',
  },
  {
    term: 'connotation',
    tr: 'çağrışım, yan anlam',
    type: 'noun',
    level: 'C1',
    example: 'The word cheap has a negative connotation in this context.',
    exampleTr: 'Cheap kelimesinin bu bağlamda olumsuz bir çağrışımı var.',
  },
  {
    term: 'discrepancy',
    tr: 'tutarsızlık, fark, uyuşmazlık',
    type: 'noun',
    level: 'C1',
    example: 'There is a discrepancy between what users say and what they actually do.',
    exampleTr: 'Kullanıcıların söyledikleriyle gerçekte yaptıkları arasında bir tutarsızlık var.',
    collocations: 'notice a discrepancy, a significant discrepancy',
  },
  {
    term: 'elaborate',
    tr: 'detaylandırmak, açmak',
    type: 'verb',
    level: 'C1',
    pattern: 'elaborate on something',
    example: 'Could you elaborate on how this would affect new learners?',
    exampleTr: 'Bunun yeni öğrenenleri nasıl etkileyeceğini biraz açabilir misin?',
  },
  {
    term: 'flawed',
    tr: 'kusurlu, hatalı',
    type: 'adjective',
    level: 'C1',
    example: 'The conclusion is based on flawed assumptions.',
    exampleTr: 'Sonuç kusurlu varsayımlara dayanıyor.',
    collocations: 'flawed logic, flawed methodology',
  },
  {
    term: 'impose',
    tr: 'dayatmak, yüklemek',
    type: 'verb',
    level: 'C1',
    pattern: 'impose limits / rules / costs',
    example: 'Strict deadlines can impose unnecessary pressure on the team.',
    exampleTr: 'Katı teslim tarihleri ekibe gereksiz baskı yükleyebilir.',
  },
  {
    term: 'incentive',
    tr: 'teşvik, motivasyon unsuru',
    type: 'noun',
    level: 'C1',
    example: 'The new pricing model gives customers an incentive to choose annual plans.',
    exampleTr: 'Yeni fiyatlandırma modeli müşterilere yıllık planları seçmeleri için teşvik sağlar.',
    collocations: 'financial incentive, strong incentive',
  },
  {
    term: 'inherent',
    tr: 'doğasında olan, yapısal',
    type: 'adjective',
    level: 'C1',
    pattern: 'inherent in something',
    example: 'There is an inherent risk in relying on a single provider.',
    exampleTr: 'Tek bir sağlayıcıya güvenmenin doğasında yapısal bir risk vardır.',
  },
  {
    term: 'notion',
    tr: 'fikir, kavram, anlayış',
    type: 'noun',
    level: 'C1',
    example: 'The notion that productivity means being busy all day is misleading.',
    exampleTr: 'Verimliliğin bütün gün meşgul olmak anlamına geldiği fikri yanıltıcıdır.',
  },
  {
    term: 'overlook',
    tr: 'gözden kaçırmak, görmezden gelmek',
    type: 'verb',
    level: 'C1',
    example: 'It is easy to overlook small usability problems during internal testing.',
    exampleTr: 'İç test sırasında küçük kullanılabilirlik sorunlarını gözden kaçırmak kolaydır.',
  },
  {
    term: 'plausible',
    tr: 'makul, olası, kulağa yatkın',
    type: 'adjective',
    level: 'C1',
    example: 'That explanation sounds plausible, but we still need data.',
    exampleTr: 'Bu açıklama makul geliyor ama yine de veriye ihtiyacımız var.',
    synonyms: 'credible, believable',
  },
  {
    term: 'preliminary',
    tr: 'ön, başlangıç niteliğinde',
    type: 'adjective',
    level: 'C1',
    example: 'The preliminary results are encouraging, but the sample size is small.',
    exampleTr: 'Ön sonuçlar umut verici ama örneklem boyutu küçük.',
    collocations: 'preliminary findings, preliminary analysis',
  },
  {
    term: 'robust',
    tr: 'sağlam, güçlü, dayanıklı',
    type: 'adjective',
    level: 'C1',
    example: 'We need a robust process for reviewing new content.',
    exampleTr: 'Yeni içerikleri incelemek için sağlam bir sürece ihtiyacımız var.',
    collocations: 'robust evidence, robust system',
  },
  {
    term: 'solely',
    tr: 'yalnızca, sadece',
    type: 'adverb',
    level: 'C1',
    example: 'We should not rely solely on test scores to measure progress.',
    exampleTr: 'Gelişimi ölçmek için yalnızca test puanlarına güvenmemeliyiz.',
  },
  {
    term: 'subtle',
    tr: 'ince, fark edilmesi zor, zarif',
    type: 'adjective',
    level: 'C1',
    example: 'There is a subtle difference between sounding confident and sounding arrogant.',
    exampleTr: 'Kendinden emin görünmek ile kibirli görünmek arasında ince bir fark vardır.',
  },
  {
    term: 'tangible',
    tr: 'somut, elle tutulur',
    type: 'adjective',
    level: 'C1',
    example: 'The training should lead to tangible improvements in speaking fluency.',
    exampleTr: 'Eğitim konuşma akıcılığında somut iyileşmelere yol açmalı.',
    collocations: 'tangible benefits, tangible results',
  },
  {
    term: 'undermine',
    tr: 'zayıflatmak, altını oymak',
    type: 'verb',
    level: 'C1',
    example: 'Inconsistent feedback can undermine a learner’s confidence.',
    exampleTr: 'Tutarsız geri bildirim bir öğrencinin özgüvenini zayıflatabilir.',
    collocations: 'undermine confidence, undermine trust',
  },
  {
    term: 'viable',
    tr: 'uygulanabilir, yaşayabilir',
    type: 'adjective',
    level: 'C1',
    example: 'The proposal is viable only if we reduce the scope.',
    exampleTr: 'Teklif ancak kapsamı azaltırsak uygulanabilir.',
    synonyms: 'workable, feasible',
  },
  {
    term: 'widespread',
    tr: 'yaygın',
    type: 'adjective',
    level: 'C1',
    example: 'There is widespread concern about the impact of automation.',
    exampleTr: 'Otomasyonun etkisi konusunda yaygın bir endişe var.',
  },
  {
    term: 'yield',
    tr: 'sonuç vermek, ürün/çıktı sağlamak',
    type: 'verb',
    level: 'C1',
    example: 'The experiment yielded unexpected results.',
    exampleTr: 'Deney beklenmedik sonuçlar verdi.',
    collocations: 'yield results, yield evidence',
  },
  {
    term: 'in light of',
    tr: 'ışığında, göz önüne alındığında',
    type: 'phrase',
    level: 'C1',
    intent: 'Yeni bilgiye dayanarak yorum yapmak',
    example: 'In light of the feedback, we decided to revise the roadmap.',
    exampleTr: 'Geri bildirim ışığında yol haritasını gözden geçirmeye karar verdik.',
  },
  {
    term: 'for the sake of',
    tr: 'uğruna, hatırına, amacıyla',
    type: 'phrase',
    level: 'C1',
    example: 'For the sake of clarity, let me restate the main point.',
    exampleTr: 'Netlik adına ana noktayı yeniden ifade edeyim.',
  },
  {
    term: 'provided that',
    tr: 'şartıyla, koşuluyla',
    type: 'phrase',
    level: 'C1',
    example: 'We can expand the feature provided that performance remains stable.',
    exampleTr: 'Performans stabil kalmak koşuluyla özelliği genişletebiliriz.',
  },
];

const additionalPhrasalVerbs: SeedCard[] = [
  {
    term: 'carry out',
    tr: 'gerçekleştirmek, yürütmek',
    type: 'phrasalVerb',
    level: 'B2',
    pattern: 'carry out research / tests / an investigation',
    example: 'The team carried out several interviews before changing the design.',
    exampleTr: 'Ekip tasarımı değiştirmeden önce birkaç görüşme gerçekleştirdi.',
    formal: 'conduct',
  },
  {
    term: 'come across',
    tr: 'rastlamak, karşılaşmak; izlenim vermek',
    type: 'phrasalVerb',
    level: 'B2',
    pattern: 'come across a word / idea / problem',
    example: 'I came across this phrase while reading an article about climate policy.',
    exampleTr: 'İklim politikasıyla ilgili bir makale okurken bu ifadeye rastladım.',
  },
  {
    term: 'cut down on',
    tr: 'azaltmak, kısmak',
    type: 'phrasalVerb',
    level: 'B2',
    pattern: 'cut down on costs / meetings / sugar',
    example: 'We need to cut down on unnecessary meetings.',
    exampleTr: 'Gereksiz toplantıları azaltmamız gerekiyor.',
    formal: 'reduce',
  },
  {
    term: 'deal with',
    tr: 'ilgilenmek, başa çıkmak',
    type: 'phrasalVerb',
    level: 'B2',
    pattern: 'deal with a problem / request / situation',
    example: 'The support team deals with urgent requests first.',
    exampleTr: 'Destek ekibi önce acil taleplerle ilgilenir.',
  },
  {
    term: 'end up',
    tr: 'sonunda ... olmak/yapmak',
    type: 'phrasalVerb',
    level: 'B2',
    pattern: 'end up doing something',
    example: 'We ended up rewriting the whole introduction.',
    exampleTr: 'Sonunda tüm girişi yeniden yazdık.',
  },
  {
    term: 'follow up',
    tr: 'takip etmek, sonrasında iletişime geçmek',
    type: 'phrasalVerb',
    level: 'B2',
    pattern: 'follow up on something / follow up with someone',
    example: 'I will follow up with the client after the meeting.',
    exampleTr: 'Toplantıdan sonra müşteriyle tekrar iletişime geçeceğim.',
  },
  {
    term: 'look into',
    tr: 'araştırmak, incelemek',
    type: 'phrasalVerb',
    level: 'B2',
    pattern: 'look into an issue / complaint / possibility',
    example: 'We are looking into the cause of the error.',
    exampleTr: 'Hatanın sebebini araştırıyoruz.',
    formal: 'investigate',
  },
  {
    term: 'point out',
    tr: 'belirtmek, dikkat çekmek',
    type: 'phrasalVerb',
    level: 'B2',
    pattern: 'point out that...',
    example: 'She pointed out that the sample size was too small.',
    exampleTr: 'Örneklem boyutunun çok küçük olduğuna dikkat çekti.',
  },
  {
    term: 'rule out',
    tr: 'ihtimal dışı bırakmak, elemek',
    type: 'phrasalVerb',
    level: 'C1',
    pattern: 'rule out an option / possibility',
    example: 'We cannot rule out the possibility that users misunderstood the question.',
    exampleTr: 'Kullanıcıların soruyu yanlış anlamış olma ihtimalini dışlayamayız.',
  },
  {
    term: 'set out',
    tr: 'açıklamak, ortaya koymak; yola çıkmak',
    type: 'phrasalVerb',
    level: 'C1',
    pattern: 'set out a plan / argument / principles',
    example: 'The report sets out the main reasons for the decline.',
    exampleTr: 'Rapor düşüşün ana sebeplerini ortaya koyuyor.',
  },
  {
    term: 'take on',
    tr: 'üstlenmek, işe almak, yeni anlam kazanmak',
    type: 'phrasalVerb',
    level: 'B2',
    pattern: 'take on responsibility / a role / staff',
    example: 'She took on more responsibility after the team lead left.',
    exampleTr: 'Takım lideri ayrıldıktan sonra daha fazla sorumluluk üstlendi.',
  },
  {
    term: 'turn down',
    tr: 'reddetmek, kısmak',
    type: 'phrasalVerb',
    level: 'B2',
    pattern: 'turn down an offer / request',
    example: 'He turned down the offer because the role was not challenging enough.',
    exampleTr: 'Rol yeterince zorlayıcı olmadığı için teklifi reddetti.',
  },
  {
    term: 'weigh up',
    tr: 'tartmak, değerlendirmek',
    type: 'phrasalVerb',
    level: 'C1',
    pattern: 'weigh up the pros and cons',
    example: 'We need to weigh up the benefits and risks before deciding.',
    exampleTr: 'Karar vermeden önce faydaları ve riskleri tartmamız gerekiyor.',
  },
  {
    term: 'come up with',
    tr: 'bulmak, üretmek',
    type: 'phrasalVerb',
    level: 'B2',
    pattern: 'come up with an idea / solution / plan',
    example: 'The team came up with a simpler way to explain the concept.',
    exampleTr: 'Ekip kavramı açıklamak için daha basit bir yol buldu.',
  },
  {
    term: 'back up',
    tr: 'desteklemek, yedeklemek',
    type: 'phrasalVerb',
    level: 'B2',
    pattern: 'back up a claim / argument / file',
    example: 'You need evidence to back up such a strong claim.',
    exampleTr: 'Bu kadar güçlü bir iddiayı desteklemek için kanıta ihtiyacın var.',
  },
  {
    term: 'narrow down',
    tr: 'seçenekleri azaltmak, daraltmak',
    type: 'phrasalVerb',
    level: 'B2',
    pattern: 'narrow down the options',
    example: 'We narrowed down the list to five possible topics.',
    exampleTr: 'Listeyi beş olası konuya indirdik.',
  },
  {
    term: 'spell out',
    tr: 'açıkça anlatmak, tek tek belirtmek',
    type: 'phrasalVerb',
    level: 'C1',
    pattern: 'spell out the consequences / details',
    example: 'The contract spells out what happens if the deadline is missed.',
    exampleTr: 'Sözleşme teslim tarihi kaçırılırsa ne olacağını açıkça belirtiyor.',
  },
  {
    term: 'bring about',
    tr: 'neden olmak, meydana getirmek',
    type: 'phrasalVerb',
    level: 'C1',
    pattern: 'bring about change / improvement',
    example: 'Small design changes can bring about a noticeable improvement.',
    exampleTr: 'Küçük tasarım değişiklikleri fark edilir bir iyileşme sağlayabilir.',
  },
];

const additionalIdioms: SeedCard[] = [
  {
    term: 'a double-edged sword',
    tr: 'hem faydası hem zararı olan şey',
    type: 'idiom',
    level: 'C1',
    example: 'Automation is a double-edged sword: it saves time but can reduce oversight.',
    exampleTr: 'Otomasyon iki ucu keskin kılıçtır: zaman kazandırır ama denetimi azaltabilir.',
  },
  {
    term: 'a steep learning curve',
    tr: 'zor ve hızlı öğrenme süreci',
    type: 'idiom',
    level: 'B2',
    example: 'The tool has a steep learning curve, but it becomes powerful once you understand it.',
    exampleTr: 'Aracın öğrenme süreci zor ama anladığında çok güçlü hale geliyor.',
  },
  {
    term: 'back to square one',
    tr: 'başa dönmek',
    type: 'idiom',
    level: 'B2',
    example: 'When the test failed, we were back to square one.',
    exampleTr: 'Test başarısız olunca başa döndük.',
  },
  {
    term: 'cut corners',
    tr: 'işi hızlı/ucuz yapmak için kaliteden kısmak',
    type: 'idiom',
    level: 'B2',
    example: 'If we cut corners now, we will pay for it later.',
    exampleTr: 'Şimdi kaliteden kısarsak bedelini sonra öderiz.',
  },
  {
    term: 'get the hang of it',
    tr: 'işin mantığını kavramak',
    type: 'idiom',
    level: 'B2',
    example: 'The grammar looks difficult, but you will get the hang of it with practice.',
    exampleTr: 'Gramer zor görünüyor ama pratikle mantığını kavrayacaksın.',
  },
  {
    term: 'in the long run',
    tr: 'uzun vadede',
    type: 'idiom',
    level: 'B2',
    example: 'In the long run, consistent practice matters more than intense study days.',
    exampleTr: 'Uzun vadede düzenli pratik yoğun çalışma günlerinden daha önemlidir.',
  },
  {
    term: 'miss the point',
    tr: 'asıl meseleyi kaçırmak',
    type: 'idiom',
    level: 'B2',
    example: 'Focusing only on the score misses the point of language learning.',
    exampleTr: 'Sadece puana odaklanmak dil öğrenmenin asıl noktasını kaçırır.',
  },
  {
    term: 'on the same page',
    tr: 'aynı fikirde/aynı anlayışta olmak',
    type: 'idiom',
    level: 'B2',
    example: 'Before we start, let’s make sure we are on the same page.',
    exampleTr: 'Başlamadan önce aynı noktada olduğumuzdan emin olalım.',
  },
  {
    term: 'put things into perspective',
    tr: 'olayları doğru bağlama oturtmak',
    type: 'idiom',
    level: 'C1',
    example: 'The comparison helps put the problem into perspective.',
    exampleTr: 'Karşılaştırma, problemi doğru bağlama oturtmaya yardımcı olur.',
  },
  {
    term: 'the bottom line',
    tr: 'en önemli nokta, net sonuç',
    type: 'idiom',
    level: 'B2',
    example: 'The bottom line is that we need more speaking practice.',
    exampleTr: 'En önemli nokta şu: daha fazla konuşma pratiğine ihtiyacımız var.',
  },
  {
    term: 'a grey area',
    tr: 'net olmayan, yoruma açık alan',
    type: 'idiom',
    level: 'C1',
    example: 'The policy is a grey area when it comes to AI-generated content.',
    exampleTr: 'AI ile üretilen içerik söz konusu olduğunda politika net olmayan bir alan.',
  },
  {
    term: 'raise the bar',
    tr: 'standardı yükseltmek',
    type: 'idiom',
    level: 'C1',
    example: 'The new examples raise the bar for the whole course.',
    exampleTr: 'Yeni örnekler tüm kursun standardını yükseltiyor.',
  },
  {
    term: 'take it for granted',
    tr: 'çantada keklik görmek, değerini fark etmemek',
    type: 'idiom',
    level: 'C1',
    example: 'Fluent speakers often take collocations for granted.',
    exampleTr: 'Akıcı konuşanlar collocation kullanımını çoğu zaman doğal kabul eder.',
  },
  {
    term: 'under the surface',
    tr: 'yüzeyin altında, görünenden daha derinde',
    type: 'idiom',
    level: 'C1',
    example: 'Under the surface, the problem is about trust rather than tools.',
    exampleTr: 'Yüzeyin altında problem araçlardan çok güvenle ilgili.',
  },
  {
    term: 'walk a fine line',
    tr: 'ince bir dengeyi gözetmek',
    type: 'idiom',
    level: 'C1',
    example: 'A teacher has to walk a fine line between correction and encouragement.',
    exampleTr: 'Bir öğretmen düzeltme ile cesaretlendirme arasında ince bir denge gözetmelidir.',
  },
];

const additionalCollocations: SeedCard[] = [
  {
    term: 'address a problem',
    tr: 'bir problemi ele almak/çözmeye çalışmak',
    type: 'collocation',
    level: 'B2',
    example: 'The update addresses a problem that many beginners reported.',
    exampleTr: 'Güncelleme birçok yeni başlayan kişinin bildirdiği bir problemi ele alıyor.',
  },
  {
    term: 'allocate resources',
    tr: 'kaynak ayırmak',
    type: 'collocation',
    level: 'C1',
    example: 'We need to allocate resources to content quality, not just design.',
    exampleTr: 'Sadece tasarıma değil, içerik kalitesine de kaynak ayırmamız gerekiyor.',
  },
  {
    term: 'bear in mind',
    tr: 'akılda tutmak',
    type: 'collocation',
    level: 'B2',
    example: 'Bear in mind that speaking fluency takes time to develop.',
    exampleTr: 'Konuşma akıcılığının gelişmesinin zaman aldığını akılda tut.',
  },
  {
    term: 'build confidence',
    tr: 'özgüven inşa etmek',
    type: 'collocation',
    level: 'B2',
    example: 'Short daily speaking tasks can build confidence quickly.',
    exampleTr: 'Kısa günlük konuşma görevleri özgüveni hızlıca inşa edebilir.',
  },
  {
    term: 'conduct research',
    tr: 'araştırma yürütmek',
    type: 'collocation',
    level: 'B2',
    example: 'The team conducted research before choosing the new content structure.',
    exampleTr: 'Ekip yeni içerik yapısını seçmeden önce araştırma yürüttü.',
  },
  {
    term: 'consider the implications',
    tr: 'sonuçları/etkileri dikkate almak',
    type: 'collocation',
    level: 'C1',
    example: 'We should consider the implications before changing the learning path.',
    exampleTr: 'Öğrenme yolunu değiştirmeden önce etkileri dikkate almalıyız.',
  },
  {
    term: 'draw attention to',
    tr: 'dikkat çekmek',
    type: 'collocation',
    level: 'B2',
    example: 'The teacher drew attention to common article mistakes.',
    exampleTr: 'Öğretmen yaygın article hatalarına dikkat çekti.',
  },
  {
    term: 'gain insight into',
    tr: 'içgörü kazanmak, daha iyi anlamak',
    type: 'collocation',
    level: 'C1',
    example: 'Interviews helped us gain insight into how learners review vocabulary.',
    exampleTr: 'Görüşmeler öğrencilerin kelime tekrarını nasıl yaptığını daha iyi anlamamıza yardım etti.',
  },
  {
    term: 'have a tendency to',
    tr: '... yapma eğiliminde olmak',
    type: 'collocation',
    level: 'B2',
    example: 'Turkish speakers have a tendency to omit articles in English.',
    exampleTr: 'Türkçe konuşanlar İngilizcede article atlama eğilimindedir.',
  },
  {
    term: 'make a distinction',
    tr: 'ayrım yapmak',
    type: 'collocation',
    level: 'C1',
    example: 'It is useful to make a distinction between accuracy and fluency.',
    exampleTr: 'Doğruluk ile akıcılık arasında ayrım yapmak faydalıdır.',
  },
  {
    term: 'meet expectations',
    tr: 'beklentileri karşılamak',
    type: 'collocation',
    level: 'B2',
    example: 'The first version did not fully meet expectations.',
    exampleTr: 'İlk sürüm beklentileri tam olarak karşılamadı.',
  },
  {
    term: 'pose a risk',
    tr: 'risk oluşturmak',
    type: 'collocation',
    level: 'C1',
    example: 'Relying on memorization alone poses a risk for speaking fluency.',
    exampleTr: 'Sadece ezbere dayanmak konuşma akıcılığı için risk oluşturur.',
  },
  {
    term: 'provide feedback',
    tr: 'geri bildirim sağlamak/vermek',
    type: 'collocation',
    level: 'B2',
    example: 'The writing mode should provide feedback without interrupting the learner.',
    exampleTr: 'Yazma modu öğrenciyi bölmeden geri bildirim sağlamalı.',
  },
  {
    term: 'reach a conclusion',
    tr: 'sonuca varmak',
    type: 'collocation',
    level: 'B2',
    example: 'It is too early to reach a conclusion based on one test.',
    exampleTr: 'Tek bir teste dayanarak sonuca varmak için çok erken.',
  },
  {
    term: 'refine an argument',
    tr: 'argümanı inceltmek/geliştirmek',
    type: 'collocation',
    level: 'C1',
    example: 'Use hedging language to refine your argument.',
    exampleTr: 'Argümanını geliştirmek için hedging ifadeleri kullan.',
  },
  {
    term: 'remain stable',
    tr: 'stabil kalmak',
    type: 'collocation',
    level: 'B2',
    example: 'Retention remained stable after the interface change.',
    exampleTr: 'Arayüz değişikliğinden sonra kullanıcı tutma stabil kaldı.',
  },
  {
    term: 'take into account',
    tr: 'dikkate almak, hesaba katmak',
    type: 'collocation',
    level: 'B2',
    example: 'The plan takes into account the learner’s limited daily time.',
    exampleTr: 'Plan, öğrencinin sınırlı günlük zamanını dikkate alıyor.',
  },
  {
    term: 'undergo a change',
    tr: 'değişim geçirmek',
    type: 'collocation',
    level: 'C1',
    example: 'The app underwent a major change when it moved from German to English.',
    exampleTr: 'Uygulama Almancadan İngilizceye geçerken büyük bir değişim geçirdi.',
  },
  {
    term: 'valid point',
    tr: 'geçerli/yerinde nokta',
    type: 'collocation',
    level: 'B2',
    example: 'That is a valid point, but it does not solve the main issue.',
    exampleTr: 'Bu yerinde bir nokta ama ana sorunu çözmüyor.',
  },
  {
    term: 'widely accepted',
    tr: 'geniş kabul görmüş',
    type: 'collocation',
    level: 'C1',
    example: 'It is widely accepted that input and output practice should support each other.',
    exampleTr: 'Input ve output pratiğinin birbirini desteklemesi gerektiği geniş kabul görür.',
  },
];

const additionalSpeakingPatterns: SeedCard[] = [
  {
    term: 'As far as I can tell,...',
    tr: 'Anladığım/görebildiğim kadarıyla...',
    type: 'phrase',
    level: 'B2',
    intent: 'Sınırlı bilgiyle yorum yapmak',
    example: 'As far as I can tell, the issue is related to timing rather than content.',
    exampleTr: 'Görebildiğim kadarıyla sorun içerikten çok zamanlamayla ilgili.',
    formal: 'Based on the available information,...',
  },
  {
    term: 'I am not entirely convinced that...',
    tr: '... olduğuna tam ikna olmadım',
    type: 'phrase',
    level: 'C1',
    intent: 'Nazik şüphe belirtmek',
    example: 'I am not entirely convinced that more flashcards alone will solve the problem.',
    exampleTr: 'Sadece daha fazla kartın problemi çözeceğine tam ikna olmadım.',
  },
  {
    term: 'It depends on what you mean by...',
    tr: '... derken ne kastettiğine bağlı',
    type: 'phrase',
    level: 'C1',
    intent: 'Tanımı netleştirmek',
    example: 'It depends on what you mean by fluent.',
    exampleTr: 'Akıcı derken ne kastettiğine bağlı.',
  },
  {
    term: 'Let me put it another way.',
    tr: 'Bunu başka şekilde ifade edeyim.',
    type: 'phrase',
    level: 'B2',
    intent: 'Yeniden açıklamak',
    example: 'Let me put it another way: the goal is not to know more words, but to use them naturally.',
    exampleTr: 'Bunu başka şekilde ifade edeyim: hedef daha fazla kelime bilmek değil, onları doğal kullanmak.',
  },
  {
    term: 'My main concern is...',
    tr: 'Benim ana endişem...',
    type: 'phrase',
    level: 'B2',
    intent: 'Endişeyi net ve profesyonel dile getirmek',
    example: 'My main concern is that the examples may be too easy for C1 learners.',
    exampleTr: 'Ana endişem, örneklerin C1 öğrencileri için fazla kolay olabilmesi.',
  },
  {
    term: 'That is a fair point.',
    tr: 'Bu yerinde/adil bir nokta.',
    type: 'phrase',
    level: 'B2',
    intent: 'Karşı tarafı kabul etmek',
    example: 'That is a fair point. We should add more collocations.',
    exampleTr: 'Bu yerinde bir nokta. Daha fazla collocation eklemeliyiz.',
  },
  {
    term: 'The way I see it,...',
    tr: 'Benim gördüğüm kadarıyla...',
    type: 'phrase',
    level: 'B2',
    intent: 'Kendi perspektifini sunmak',
    example: 'The way I see it, speaking patterns are more useful than isolated sentences.',
    exampleTr: 'Benim gördüğüm kadarıyla konuşma kalıpları izole cümlelerden daha faydalı.',
  },
  {
    term: 'To a certain extent,...',
    tr: 'Belirli bir ölçüde...',
    type: 'phrase',
    level: 'C1',
    intent: 'Kısmi kabul belirtmek',
    example: 'To a certain extent, memorization is useful, but production matters more.',
    exampleTr: 'Belirli bir ölçüde ezber faydalı ama üretim daha önemli.',
  },
  {
    term: 'What makes this difficult is...',
    tr: 'Bunu zorlaştıran şey...',
    type: 'phrase',
    level: 'B2',
    intent: 'Problem analizi yapmak',
    example: 'What makes this difficult is that the words are familiar but the usage is not.',
    exampleTr: 'Bunu zorlaştıran şey, kelimelerin tanıdık ama kullanımın tanıdık olmaması.',
  },
  {
    term: 'I would be inclined to...',
    tr: 'Ben ... yapmaya daha yatkın olurdum',
    type: 'phrase',
    level: 'C1',
    intent: 'Yumuşak öneri belirtmek',
    example: 'I would be inclined to start with B2 collocations before adding C1 idioms.',
    exampleTr: 'C1 idiom eklemeden önce B2 collocation’larla başlamaya daha yatkın olurdum.',
  },
  {
    term: 'There is more to it than that.',
    tr: 'Mesele bundan ibaret değil.',
    type: 'phrase',
    level: 'C1',
    intent: 'Aşırı basitleştirmeye karşı çıkmak',
    example: 'There is more to it than that; fluency also depends on rhythm and confidence.',
    exampleTr: 'Mesele bundan ibaret değil; akıcılık ritim ve özgüvene de bağlı.',
  },
  {
    term: 'Could we take a step back?',
    tr: 'Bir adım geri çekilip bakabilir miyiz?',
    type: 'phrase',
    level: 'C1',
    intent: 'Tartışmayı yeniden çerçevelemek',
    example: 'Could we take a step back and define what success means here?',
    exampleTr: 'Bir adım geri çekilip burada başarının ne anlama geldiğini tanımlayabilir miyiz?',
  },
  {
    term: 'I would not go so far as to say that...',
    tr: '... diyecek kadar ileri gitmezdim',
    type: 'phrase',
    level: 'C1',
    intent: 'İddianın gücünü sınırlamak',
    example: 'I would not go so far as to say that grammar is less important than vocabulary.',
    exampleTr: 'Gramerin kelimeden daha az önemli olduğunu söyleyecek kadar ileri gitmezdim.',
  },
  {
    term: 'The key thing to remember is...',
    tr: 'Hatırlanması gereken en önemli şey...',
    type: 'phrase',
    level: 'B2',
    intent: 'Ana fikri vurgulamak',
    example: 'The key thing to remember is that examples make vocabulary usable.',
    exampleTr: 'Hatırlanması gereken en önemli şey, örneklerin kelimeyi kullanılabilir hale getirmesidir.',
  },
  {
    term: 'If I understand you correctly,...',
    tr: 'Seni doğru anladıysam...',
    type: 'phrase',
    level: 'B2',
    intent: 'Anladığını kontrol etmek',
    example: 'If I understand you correctly, you want more cards based on real learner resources.',
    exampleTr: 'Seni doğru anladıysam, gerçek öğrenme kaynaklarına dayalı daha fazla kart istiyorsun.',
  },
];

export const LIST_B2_VOCAB: VocabList = {
  id: 'b2-core-vocabulary',
  title: 'B2 Core Vocabulary',
  isDefault: true,
  words: mapCards('b2_vocab', [...b2Vocabulary, ...additionalB2Vocabulary]),
};

export const LIST_COMMON_VERBS: VocabList = {
  id: 'common-english-verbs',
  title: 'Common English Verbs',
  isDefault: true,
  words: createCommonVerbCards(),
};

export const LIST_C1_VOCAB: VocabList = {
  id: 'c1-advanced-vocabulary',
  title: 'C1 Advanced Vocabulary',
  isDefault: true,
  words: mapCards('c1_vocab', [...c1Vocabulary, ...additionalC1Vocabulary]),
};

export const LIST_PHRASAL_VERBS: VocabList = {
  id: 'phrasal-verbs',
  title: 'Phrasal Verbs',
  isDefault: true,
  words: mapCards('phrasal', [...phrasalVerbs, ...additionalPhrasalVerbs]),
};

export const LIST_IDIOMS: VocabList = {
  id: 'idioms-natural-english',
  title: 'Idioms & Natural English',
  isDefault: true,
  words: mapCards('idiom', [...idioms, ...additionalIdioms]),
};

export const LIST_COLLOCATIONS: VocabList = {
  id: 'collocations',
  title: 'Collocations',
  isDefault: true,
  words: mapCards('collocation', [...collocations, ...additionalCollocations]),
};

export const LIST_SPEAKING_PATTERNS: VocabList = {
  id: 'speaking-patterns',
  title: 'Speaking Patterns',
  isDefault: true,
  words: mapCards('speaking', [...speakingPatterns, ...additionalSpeakingPatterns]),
};

export const LIST_MY_NEW_WORDS: VocabList = {
  id: 'my-new-words',
  title: 'My New Words',
  isDefault: true,
  words: [],
};
